### PR TITLE
Dockerize project

### PR DESCRIPTION
**Pull request by ppirch**
### What does this changes

- Change  docker image and command 
- Add main in main.py
- Add docker compose file

### CODE REVIEW

**Comment by ppirch** [comment]
I switch from alpine and use python:3.7 instead. Because  alpine has not provided gcc.

**Comment by wannaphong** [comment]
Thank you for this pull requset. Can you fix conflicts? @ppirch

**Comment by ppirch** [comment]
> Thank you for this pull requset. Can you fix conflicts? @ppirch

Yes, I Can.

**Comment by ppirch** [comment]
> > Thank you for this pull requset. Can you fix conflicts? @ppirch
> 
> Yes, I Can.

Sorry, I can't 

> > Thank you for this pull requset. Can you fix conflicts? @ppirch
> 
> Yes, I Can.

Sorry, I can not click on resolve conflicts button, It said `only those with write access to this repository can merge pull requests`.But I think If you merge from below it will be ok.

**Pull request merged**
